<a href="https://colab.research.google.com/github/Cann-Emma/DS1002-zgb8ts/blob/main/DIY1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
zero_array= np.zeros([3,2])
print(zero_array)
inte_array= np.zeros((3,2), dtype=np.int32)
print(inte_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]
 [0 0]]


In [5]:
#data type has to be homogenous
data= [4, 8, 12, 16, 20]
arr2= np.array(data)
arr2

array([ 4,  8, 12, 16, 20])

In [10]:
# shape returns the dimension of your array and how many elements are in each array
dime2= [[2,4,6,8,10], [5,10,15,20,25]]
arr1= np.array(dime2)
print(arr1.ndim)
print(arr1.shape)

2
(2, 5)
